# Generated by Django 3.1.5 on 2021-03-30 16:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('adoption', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
