# Generated by Django 3.1.5 on 2021-03-11 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0002_evaluation_animal_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluation',
            name='animal_id',
        ),
        migrations.AddField(
            model_name='evaluation',
            name='animal_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adoption.animal'),
        ),
    ]
