# Generated by Django 3.1.5 on 2021-03-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0004_remove_request_eval_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='pickup_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(default='pending', max_length=10),
        ),
    ]
