# Generated by Django 3.1.5 on 2021-03-20 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0006_auto_20210320_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
