# Generated by Django 3.1.5 on 2021-03-22 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0007_auto_20210321_0104'),
    ]

    operations = [
        migrations.CreateModel(
            name='notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='evaluation',
            old_name='animal_id',
            new_name='animal',
        ),
    ]
