# Generated by Django 3.1.5 on 2021-03-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('adoption', '0008_auto_20210322_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluation',
            name='evaluation_details',
        ),
        migrations.AddField(
            model_name='evaluation',
            name='answer1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='answer10',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='answer2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='answer3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='answer4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='answer5',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='answer6',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='answer7',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='answer8',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='answer9',
            field=models.TextField(blank=True),
        ),
    ]
