# Generated by Django 3.1.5 on 2021-03-28 16:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('adoption', '0009_auto_20210328_2226'),
    ]

    operations = [
        migrations.DeleteModel(
            name='notifications',
        ),
    ]
