# Generated by Django 3.1.5 on 2021-04-02 12:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('adminzone', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminpanel',
            name='org_address',
        ),
        migrations.RemoveField(
            model_name='adminpanel',
            name='org_city',
        ),
        migrations.RemoveField(
            model_name='adminpanel',
            name='org_location',
        ),
        migrations.RemoveField(
            model_name='adminpanel',
            name='org_name',
        ),
        migrations.RemoveField(
            model_name='adminpanel',
            name='org_report',
        ),
        migrations.RemoveField(
            model_name='adminpanel',
            name='org_state',
        ),
    ]
