# Generated by Django 3.1.5 on 2021-04-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('adminzone', '0002_auto_20210402_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminpanel',
            name='org_address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='adminpanel',
            name='org_city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='adminpanel',
            name='org_location',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='adminpanel',
            name='org_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='adminpanel',
            name='org_report',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='adminpanel',
            name='org_state',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
