# Generated by Django 3.1.5 on 2021-04-02 16:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('adminzone', '0003_auto_20210402_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminpanel',
            name='org_zipcode',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='adminpanel',
            name='org_city',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='adminpanel',
            name='org_location',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='adminpanel',
            name='org_report',
            field=models.FileField(default='admindocs/default.jpg', upload_to='admindocs'),
        ),
        migrations.AlterField(
            model_name='adminpanel',
            name='org_state',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
