# Generated by Django 3.1.5 on 2021-04-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('adminzone', '0004_auto_20210402_2153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminpanel',
            old_name='org_report',
            new_name='org_docs',
        ),
        migrations.AddField(
            model_name='adminpanel',
            name='org_phone',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
