# Generated by Django 3.1.5 on 2021-04-02 16:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('adminzone', '0005_auto_20210402_2158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminpanel',
            old_name='org_docs',
            new_name='org_doc',
        ),
    ]
