# Generated by Django 3.1.5 on 2021-03-28 13:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0002_auto_20210328_1829'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
