# Generated by Django 3.1.5 on 2021-03-28 14:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0004_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
