# Generated by Django 3.1.5 on 2021-03-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('accounts', '0005_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='userDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=15)),
                ('state', models.CharField(blank=True, max_length=15)),
                ('phone_number', models.CharField(blank=True, max_length=12)),
            ],
        ),
    ]
